name: generate-html

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0 - 3.9.0'
      - name: Convert Markdown to html
        run: |
          pip3 install -r requirements.txt
          python3 scripts/markdown-me.py README.md index.html

      - name: Commit Pages docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          file_pattern: "docs/"
          commit_message: "Publishing pages from Markdown"
          add_options: 'docs/' 