name: terraform-pr

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: hashicorp/setup-terraform@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN}}
          aws-region: eu-west-1

      - name: Terraform apply
        id: apply
        run: apply
        continue-on-error: true
