name: terraform-pr

on:
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.TF_VAR_CLOUDFLARE_ZONE_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN}}
          aws-region: eu-west-1
          role-duration-seconds: 3600

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform

      - name: Commit Terraform
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Terraform formatting"